config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :tasks
  end
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_scope :user do 
  #   root to: 'devise/sessions#create'
  # end
  root to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: true
  validates_uniqueness_of :title, message: "already exists"
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    has_one :user, through: :category
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :page
  before_action :set_category, only: %i[ show edit update destroy]

  def index
    @categories = current_user.categories
    @tasks = current_user.tasks
    @today = @tasks.where('date = ?', Date.current)
  end

  def show
    @tasks = @category.tasks
  end

  def new
    @category = current_user.categories.build
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)

      if @category.save
        redirect_to categories_path, notice: "Category was successfully created."
      else
       render :new
    end
  end

  def update
      if @category.update(category_params)
       redirect_to categories_path, notice: "Category was successfully updated."
      else
        render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: "Category was successfully deleted." 
  end

  private
 
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category, except: %i[update destroy]
    before_action :set_task, only: %i[edit update destroy show]
    before_action :sort_task, only: %i[index show]
  
    def index
        @tasks = @category.tasks  
    end
  
    def show
    end
  
    def new
      @task = @category.tasks.build
    end
  
    def edit
    end
  
    def create
      @task = @category.tasks.create(task_params)
  
        if @task.save
          redirect_to category_tasks_path(@category), notice: "Task was successfully created."
        else
         render :new
      end
    end
  
    def update
        if @task.update(task_params)
          redirect_to category_tasks_path, notice: "Successfully updated task!"
        else
         render :edit
      end
    end
  
    def destroy
      @task.destroy
  
       redirect_to category_tasks_path, notice: "Task was successfully deleted."
    end
  
    private
      def set_category
        @category = current_user.categories.find(params[:category_id])
      end

      def set_task
        @category = current_user.categories.find(params[:category_id])
        @task = @category.tasks.find(params[:id])
      end
  
      def task_params
        params.require(:task).permit(:title, :body, :date, :category_id, :checked)
      end

      def sort_task
        @today = @category.tasks.where('date = ?', Date.current)
        @scheduled = @category.tasks.where('date > ?', Date.current)
        @overdue = @category.tasks.where('date < ?', Date.current)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <% category.errors.each do |error| %>
        <div><%= error.full_message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_field :title, placeholder: "Title" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="modal-category">
  <div class="overlay">
    <div class="container">
      <div class="title">
        <div class="flex">
        <div>Edit Category</div>
        <div class="name"><%= @category.title%></div>
        </div>
        <%= link_to categories_path do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
      <div class="form">
        <%= render 'form', category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="categories">
  <div class="nav">
    <div class="title">
      <i class="fa-solid fa-list-check"></i>
      érgo
    </div>
    <div class="options">
      <ul>
        <li><i class="fa-solid fa-user-tie"></i><%= current_user.email %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-right-from-bracket"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="main">
    <div class="left">
      <div class="title"><i class="fa-solid fa-clipboard-list"></i>Task Categories</div>
      <% if flash.notice.blank? %>
      <% else %>
        <div class="notice"><%= notice %></div>
      <% end %>
      <% if @categories.any? %>
        <div class="container">
          <% @categories.order(created_at: :desc).each do |category| %>
            <div class="box">
              <div class="category"> <%= category.title %> </div>
              <div class="details">
                <div class="task-count"><i class="fa-solid fa-thumbtack"></i>
                  <%= pluralize(category.tasks.count, "Task") %></div>
                <% category.tasks.order(updated_at: :desc).limit(1).each do |task| %>
                  <div> <i class="fa-solid fa-arrows-rotate"></i>Last updated: <%= task.updated_at.strftime("%b %d, %Y") %>
                  </div>
                <% end %>
              </div>
              <div class="options">
                <%= link_to category_tasks_path(category), class: "show-category" do %>
                  <div>
                    <i class="fa-solid fa-list-ul"></i></div>
                <% end %>
                <%= link_to edit_category_path(category), class: "edit-category" do %>
                  <div><i class="fa-solid fa-pen-to-square"></i></div>
                <% end %>
                <%= link_to category, class: "delete-category", method: :delete, data: { confirm: "Are you sure you want to delete this category? This can't be undone." } do %>
                  <div><i class="fa-solid fa-trash-can"></i></div>
                <% end %>
              </div>
            </div>
          <% end %>
          <%= link_to new_category_path, class: "add-category" do %>
            <div class="box new">
              <i class="fa-solid fa-plus"></i>
            </div>
          <% end %>
        </div>
      <% else %>
        <%= link_to new_category_path, class: "add-category" do %>
          <div class="add-new">
            + Add Category
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="right">
      <div class="title">
        <i class="fa-solid fa-calendar-check"></i>
        Today's Tasks
      </div>
      <div class="main">
        <% if @today.any? %>
          <div class="container">
            <% @today.order(created_at: :asc).each do |task| %>
              <%= link_to category_tasks_path(task.category), class: "task" do %>
                <div class="name"> <%= task.title %> </div>
                <div class="status">
                  <% if task.checked? %>
                    <div class="completed">Completed</div>
                  <% else %>
                    <div class="ongoing">Ongoing</div>
                  <% end %>
                </div>
                <div class="options">
                <div class="category">  <%= task.category.title %>  </div></div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="no-task">
            No Today's Task
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/categories/new.html.erb
<div class="modal-category">
  <div class="overlay">
    <div class="container">
      <div class="title">
        <div class="flex">
          <div>Add New Category</div>
          <% if @category.title.blank? || @category.errors.any? %>
          <% else %>
          <div class="name"><%= @category.title%></div> <% end %>
        </div>
        <%= link_to categories_path do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
      <div class="form">
        <%= render 'form', category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Érgo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/854e38c6b1.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task, url: url do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
        <% task.errors.each do |error| %>
          <div><%= error.full_message %></div>
        <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_field :title, placeholder: "Title"%>
  </div>
  <div class="field">
    <%= form.text_area :body, placeholder: "Notes"%>
  </div>
  <div class="field">
    <i class="fa-solid fa-calendar-minus"></i>
    <%= form.date_select :date %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="modal-task">
  <div class="overlay">
    <div class="container">
      <div class="title">
        <div class="flex">
        <div>Edit Task</div>
        <div class="name"><%= @task.title%></div>
        </div>
        <%= link_to category_tasks_path(@category) do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
      <div class="form">
        <%= render 'form', task: @task, url: category_task_path %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="tasks">
  <div class="nav">
    <div class="title">
      <i class="fa-solid fa-list-check"></i>
      érgo
    </div>
    <div class="options">
      <ul>
        <li><i class="fa-solid fa-user-tie"></i><%= current_user.email %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-right-from-bracket"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="main">
    <div class="title">
      <%= link_to categories_path do %>
        <div class="category">
          <i class="fa-solid fa-caret-left"></i>
          <%= @category.title %>
        </div>
      <% end %>
      <%= link_to new_category_task_path(@category) do %>
        <div class="new">+ Add New Task
        </div>
      <% end %>
    </div>
    <% if flash.notice.blank? %>
    <% else %>
      <div class="notice"><%= notice %></div>
    <% end %>
    <div class="container">
      <div class="task-title today-title">
        <div><i class="fa-regular fa-calendar-check"></i>Today's Tasks</div>
        <div class="count">
          <div class="completed"><%= @today.where(checked: "1").count %> Completed</div>
          <div class="incomplete incomplete-today"><%= @today.count - @today.where(checked: "1").count %> Ongoing</div>
        </div>
      </div>
      <div class="box">
        <% if @today.any? %>
          <% @today.order(checked: :asc).each do |task| %>
            <div class="<%= task.checked ? "task-checked" : "task" %>">
              <div class="check">
                <%= form_with model: task, url: category_task_path(task.category, task) do |f| %>
                  <%= f.check_box :checked, onchange: "this.form.submit()" %>
                <% end %>
                <div class="<%= task.checked ? "name-checked" : "name" %>"><%= task.title %></div>
              </div>
              <div class="<%= task.checked ? "date-checked" : "date" %>"><i class="fa-regular fa-calendar"></i><%= task.date.strftime("%b %d, %Y") %></div>
              <div class="options">
                <div>
                  <% if task.checked %>
                  <% else %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <% if task.checked %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% else %>
                    <%= link_to edit_category_task_path(@category, task), class: "edit-task" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <%= link_to category_task_path(@category, task), class: "delete-task", method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% elsif %>
          <div class="no">No Today's Task</div>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="task-title schedule-title">
        <div><i class="fa-regular fa-calendar-days"></i>Scheduled Tasks</div>
        <div class="count">
          <div class="completed"><%= @scheduled.where(checked: "1").count %> Completed</div>
          <div class="incomplete"><%= @scheduled.count - @scheduled.where(checked: "1").count %> Pending</div>
        </div>
      </div>
      <div class="box">
        <% if @scheduled.any? %>
          <% @scheduled.order(checked: :asc).each do |task| %>
            <div class="<%= task.checked ? "task-checked" : "task" %>">
              <div class="check">
                <%= form_with model: task, url: category_task_path(task.category, task) do |f| %>
                  <%= f.check_box :checked, onchange: "this.form.submit()" %>
                <% end %>
                <div class="<%= task.checked ? "name-checked" : "name" %>"><%= task.title %></div>
              </div>
              <div class="<%= task.checked ? "date-checked" : "date" %>"><i class="fa-regular fa-calendar"></i><%= task.date.strftime("%b %d, %Y") %></div>
              <div class="options">
                <div>
                  <% if task.checked %>
                  <% else %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <% if task.checked %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% else %>
                    <%= link_to edit_category_task_path(@category, task), class: "edit-task" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <%= link_to category_task_path(@category, task), class: "delete-task", method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% elsif %>
          <div class="no">No Scheduled Task</div>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="task-title overdue-title">
        <div><i class="fa-regular fa-calendar-xmark"></i>Overdue Tasks</div>
        <div class="count">
          <div class="completed"><%= @overdue.where(checked: "1").count %> Completed</div>
          <div class="incomplete incomplete-overdue"><%= @overdue.count - @overdue.where(checked: "1").count %> Delayed</div>
        </div>
      </div>
      <div class="box">
        <% if @overdue.any? %>
          <% @overdue.order(checked: :asc).each do |task| %>
            <div class="<%= task.checked ? "task-checked" : "task" %>">
              <div class="check">
                <%= form_with model: task, url: category_task_path(task.category, task) do |f| %>
                  <%= f.check_box :checked, onchange: "this.form.submit()" %>
                <% end %>
                <div class="<%= task.checked ? "name-checked" : "name" %>"><%= task.title %></div>
              </div>
              <div class="<%= task.checked ? "date-checked" : "date" %>"><i class="fa-regular fa-calendar"></i><%= task.date.strftime("%b %d, %Y") %></div>
              <div class="options">
                <div>
                  <% if task.checked %>
                  <% else %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <% if task.checked %>
                    <%= link_to category_task_path(@category, task), class: "show-task" do %>
                      <i class="fa-solid fa-list-ul"></i>
                    <% end %>
                  <% else %>
                    <%= link_to edit_category_task_path(@category, task), class: "edit-task" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <%= link_to category_task_path(@category, task), class: "delete-task", method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% elsif %>
          <div class="no">No Overdue Task</div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/tasks/new.html.erb
<div class="modal-task">
  <div class="overlay">
    <div class="container">
      <div class="title">
        <div class="flex">
        <div>New Task</div>
        <div class="name"><%= @category.title%></div>
        </div>
        <%= link_to category_tasks_path(@category) do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
      <div class="form">
        <%= render 'form', task: @task, url: category_tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="modal-task">
  <div class="overlay">
    <div class="container">
      <div class="title">
        <div class="flex">
          <div><%= @task.title %></div>
          <div class="names">
            <% if @today.include?(@task) %>
              <div class="today">Today's Task</div>
            <% elsif @scheduled.include?(@task) %>
              <div class="scheduled">Scheduled Task</div>
            <% else %>
              <div class="overdue">Overdue Task</div>
            <% end %>
          </div>
        </div>
        <%= link_to category_tasks_path(@category) do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
      <div class="notice"><%= notice %></div>
      <div class="main">
        
          <div class="textarea">  <%= @task.body %>
        </div>
        <div class="date">  <i class="fa-solid fa-calendar-day"></i><%= @task.date.strftime("%b %m, %Y") %>
        </div>
        <%= link_to edit_category_task_path(@category, @task) do %>
        <div class="edit-btn">Edit</div>
        <% end %>
      </div>
    </div>
  </div>
</div>